variable "env" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "allow_cidr" {}
variable "component" {}
variable "app_port" {}
variable "max_size" {}
variable "min_size" {}
variable "health_check_grace_period" {}
variable "instance_type" {}